---
region: "eu-west-2"
component: "open-policy-agent"

repository_name: 'ifbk-test/opa-aws'

state_bucket_name: "infrablocks-%{hiera('component')}-%{deployment_identifier}"
secrets_bucket_name: "%{hiera('state_bucket_name')}"

repository_state_bucket_region: "%{hiera('region')}"
repository_state_bucket_name: "%{hiera('state_bucket_name')}"
repository_state_bucket_is_encrypted: "true"
repository_state_key: "repository/deployments/%{deployment_identifier}.tfstate"
