---
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{deployment_identifier}"

  image_tag: "%{hiera('image_tag')}"

  repository_state_bucket_name: "%{hiera('repository_state_bucket_name')}"
  repository_state_key: "%{hiera('repository_state_key')}"
  repository_state_bucket_region: "%{hiera('repository_state_bucket_region')}"

backend_config:
  region: "%{hiera('lambda_state_bucket_region')}"
  bucket: "%{hiera('lambda_state_bucket_name')}"
  encrypt: "%{hiera('lambda_state_bucket_is_encrypted')}"
  key: "%{hiera('lambda_state_key')}"
