---
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"

  repository_name: "%{hiera('repository_name')}"

backend_config:
  region: "%{hiera('repository_state_bucket_region')}"
  bucket: "%{hiera('repository_state_bucket_name')}"
  encrypt: "%{hiera('repository_state_bucket_is_encrypted')}"
  key: "%{hiera('repository_state_key')}"
